services:
  - type: web
    name: centralprocure-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        sync: false
      - key: NEXT_PUBLIC_APP_BASE_PATH
        sync: false
