-- Seed tenders (PostgreSQL)
INSERT INTO vendor_sourcing.tenders (
    tender_id,
    title,
    description,
    category,
    status,
    budget,
    specifications,
    eligibility_criteria,
    evaluation_criteria,
    publish_date,
    opening_date,
    closing_date,
    created_by,
    updated_by
)
SELECT *
FROM (
    VALUES
        (
            '4e5c2a1f-8b5f-4c3a-9c2f-1a2b3c4d5e01'::UUID,
            'Border Surveillance Upgrade',
            'Supply and installation of border surveillance systems, sensors, and command dashboards.',
            'Security',
            'Published',
            250000000.00,
            'Thermal cameras, UAVs, perimeter sensors',
            'ISO 27001 certified, prior government deployments',
            '70% technical, 30% financial',
            NOW() - INTERVAL '20 days',
            NOW() - INTERVAL '15 days',
            NOW() + INTERVAL '15 days',
            'seed',
            'seed'
        ),
        (
            '6f7a8b9c-0d1e-4f2a-9b3c-4d5e6f7a8b02'::UUID,
            'HQ Network Refresh',
            'Upgrade HQ core network switches, firewalls, and cabling.',
            'ICT',
            'Draft',
            90000000.00,
            'Core switches, next-gen firewalls, cabling',
            'OEM authorization and ICT compliance certifications',
            '60% technical, 40% financial',
            NULL,
            NULL,
            NULL,
            'seed',
            'seed'
        ),
        (
            '7a6b5c4d-3e2f-4a1b-8c7d-6e5f4a3b2c03'::UUID,
            'Passport Printing Supplies',
            'Supply of secure passport printing materials and consumables.',
            'Logistics',
            'Published',
            120000000.00,
            'Secure paper, holograms, inks',
            'Security clearance and compliance with ISO 14298',
            '65% technical, 35% financial',
            NOW() - INTERVAL '30 days',
            NOW() - INTERVAL '25 days',
            NOW() + INTERVAL '5 days',
            'seed',
            'seed'
        ),
        (
            '8c9d0e1f-2a3b-4c5d-8e9f-0a1b2c3d4e04'::UUID,
            'Vehicle Fleet Maintenance',
            'Comprehensive maintenance and servicing for operational vehicles.',
            'Transport',
            'Closed',
            42000000.00,
            'OEM spare parts, scheduled servicing',
            'Authorized service centers and OEM parts',
            '50% technical, 50% financial',
            NOW() - INTERVAL '120 days',
            NOW() - INTERVAL '110 days',
            NOW() - INTERVAL '70 days',
            'seed',
            'seed'
        ),
        (
            '9d8c7b6a-5f4e-4d3c-8b2a-1c0d9e8f7a05'::UUID,
            'Data Center UPS Upgrade',
            'Procurement of UPS systems for data center resilience.',
            'ICT',
            'Awarded',
            68000000.00,
            'Tier III UPS, battery banks',
            'Certified OEM partners',
            '70% technical, 30% financial',
            NOW() - INTERVAL '150 days',
            NOW() - INTERVAL '140 days',
            NOW() - INTERVAL '100 days',
            'seed',
            'seed'
        ),
        (
            '0a1b2c3d-4e5f-4a6b-9c8d-7e6f5a4b3c06'::UUID,
            'Border Post Renovation',
            'Renovation of priority border post facilities.',
            'Infrastructure',
            'Published',
            310000000.00,
            'Structural upgrades, power backup',
            'Registered construction firms with Class A rating',
            '60% technical, 40% financial',
            NOW() - INTERVAL '12 days',
            NOW() - INTERVAL '7 days',
            NOW() + INTERVAL '28 days',
            'seed',
            'seed'
        ),
        (
            '1b2c3d4e-5f6a-4b7c-8d9e-0f1a2b3c4d07'::UUID,
            'Biometric Enrollment Kits',
            'Supply of biometric enrollment kits for field stations.',
            'Security',
            'Draft',
            55000000.00,
            'Fingerprint scanners, cameras, rugged laptops',
            'OEM warranty and field support coverage',
            '70% technical, 30% financial',
            NULL,
            NULL,
            NULL,
            'seed',
            'seed'
        ),
        (
            '2c3d4e5f-6a7b-4c8d-9e0f-1a2b3c4d5e08'::UUID,
            'Facility Energy Optimization',
            'Energy efficiency retrofit for HQ and regional offices.',
            'Facilities',
            'Cancelled',
            26000000.00,
            'LED retrofits, smart meters',
            'Energy audit certification',
            '50% technical, 50% financial',
            NOW() - INTERVAL '200 days',
            NOW() - INTERVAL '190 days',
            NOW() - INTERVAL '160 days',
            'seed',
            'seed'
        ),
        (
            '3d4e5f6a-7b8c-4d9e-8f0a-1b2c3d4e5f09'::UUID,
            'Mobile Patrol Boats',
            'Procurement of patrol boats for coastal border security.',
            'Marine',
            'Published',
            210000000.00,
            'Shallow-water patrol boats, navigation kits',
            'Maritime safety certification and OEM support',
            '65% technical, 35% financial',
            NOW() - INTERVAL '8 days',
            NOW() - INTERVAL '5 days',
            NOW() + INTERVAL '25 days',
            'seed',
            'seed'
        ),
        (
            '4f5e6a7b-8c9d-4e0f-9a1b-2c3d4e5f6a10'::UUID,
            'Training Simulation Labs',
            'Design and setup of simulation labs for officer training.',
            'Training',
            'Published',
            47000000.00,
            'Simulation hardware, training software licenses',
            'Prior gov training lab deployments',
            '60% technical, 40% financial',
            NOW() - INTERVAL '16 days',
            NOW() - INTERVAL '12 days',
            NOW() + INTERVAL '18 days',
            'seed',
            'seed'
        )
) AS seed_rows (
    tender_id,
    title,
    description,
    category,
    status,
    budget,
    specifications,
    eligibility_criteria,
    evaluation_criteria,
    publish_date,
    opening_date,
    closing_date,
    created_by,
    updated_by
)
WHERE NOT EXISTS (
    SELECT 1
    FROM vendor_sourcing.tenders t
    WHERE t.title = seed_rows.title
      AND t.category = seed_rows.category
);
