\set ON_ERROR_STOP on

CREATE EXTENSION IF NOT EXISTS pgcrypto;

\echo Applying schema migrations...
\i /docker-entrypoint-initdb.d/database_schema/migrations/001_identity_roles_internal_users.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/002_add_user_login_security.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/003_procurement_plans.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/004_vendor_sourcing_tenders.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/005_vendor_sourcing_bid_opening.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/006_vendor_sourcing_bids.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/007_requisitions.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/008_post_award_contracts.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/009_post_award_inspections.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/010_evaluation_reports.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/011_identity_vendors.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/012_identity_vendor_functions_fix.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/013_cleanup_duplicate_bids.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/013_identity_update_vendor_profile.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/013_vendor_sourcing_bid_unique.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/014_evaluation_actions.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/014_identity_compliance_history.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/015_budget_ledger.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/016_app_items_thresholds_bpp_and_tender_budget.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/017_update_budget_and_workflow_functions.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/018_fix_requisition_app_item_id.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/019_reconcile_legacy_procurement_plan_items_and_tender_routines.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/020_contract_milestones.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/021_expand_identity_roles_for_ppa_alignment.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/022_harden_bid_opening_session_state.sql
\i /docker-entrypoint-initdb.d/database_schema/migrations/023_procurement_workflow_blueprint_tables.sql

\echo Applying stored procedures and functions...
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/BudgetLedger_Functions.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/CreateBidOpeningSession_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/CreateProcurementPlan_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/CreateProcurementPlanItem_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/CreateRequisition_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/CreateRole_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/CreateTender_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/DeactivateRole_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/DeleteProcurementPlan_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/DeleteProcurementPlanItem_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/DeleteRole_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetBidOpeningSessionDetails_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetBidOpeningSessions_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetComplianceDocumentHistory_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetContractAwardDetails_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetContractAwards_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetContractDetails_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetContractMilestones_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetContracts_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetEvaluationReportDetails_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetEvaluationReports_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetInspectionDetails_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetInspections_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetOpenTenders_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetProcurementPlanItems_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetProcurementPlans_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetRequisitionDetails_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetRequisitionLineItems_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetRequisitions_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetRoles_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetSubmittedBids_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetTenderDetails_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetTenders_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetVendorComplianceDocuments_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/GetVendorProfile_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/InternalLogin_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/LogContractMilestone_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/LoginVendor_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/PublishContractAward_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/PublishTender_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/RegisterInternalUser_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/RegisterVendor_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/SubmitBid_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/UpdateBidOpeningSession_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/UpdateInternalUserRole_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/UpdateProcurementPlan_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/UpdateProcurementPlanItem_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/UpdateRequisition_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/UpdateRole_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/UpdateTender_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/UpdateVendorProfile_SP.sql
\i /docker-entrypoint-initdb.d/database_schema/stored_procedures/UploadComplianceDocument_SP.sql

\echo Applying seed data...
\i /docker-entrypoint-initdb.d/database_schema/seed/001_roles.sql
\i /docker-entrypoint-initdb.d/database_schema/seed/002_internal_admin.sql
\i /docker-entrypoint-initdb.d/database_schema/seed/003_internal_users_departments.sql
\i /docker-entrypoint-initdb.d/database_schema/seed/004_internal_users_remaining.sql
\i /docker-entrypoint-initdb.d/database_schema/seed/005_vendors.sql
\i /docker-entrypoint-initdb.d/database_schema/seed/006_procurement_plans.sql
\i /docker-entrypoint-initdb.d/database_schema/seed/007_tenders.sql
\i /docker-entrypoint-initdb.d/database_schema/seed/008_bid_opening_sessions.sql
\i /docker-entrypoint-initdb.d/database_schema/seed/009_requisitions.sql
\i /docker-entrypoint-initdb.d/database_schema/seed/010_post_award_contracts.sql
\i /docker-entrypoint-initdb.d/database_schema/seed/011_post_award_inspections.sql
\i /docker-entrypoint-initdb.d/database_schema/seed/012_evaluation_reports.sql
