import type {
  WorkflowPhaseResult,
  WorkflowStateResult,
  WorkflowTransitionResult,
  WorkflowRoleTaskResult,
  WorkflowThresholdBandResult,
  WorkflowBlueprintResult,
} from './types.js';

const PHASES: WorkflowPhaseResult[] = [
  {
    phase_key: 'app_planning',
    title: 'APP Planning',
    description: 'Need capture, committee review, and APP approval.',
    sequence: 1,
  },
  {
    phase_key: 'threshold_control',
    title: 'Threshold Control',
    description: 'CGIS, Tenders Board, BPP gate, and procurement method validation.',
    sequence: 2,
  },
  {
    phase_key: 'procurement_execution',
    title: 'Procurement Execution',
    description: 'Advert/invitation, opening, evaluation, and approval routing.',
    sequence: 3,
  },
  {
    phase_key: 'post_award',
    title: 'Post-Award',
    description: 'Award publication, contract delivery, inspection, and payment controls.',
    sequence: 4,
  },
  {
    phase_key: 'review_and_oversight',
    title: 'Review and Oversight',
    description: 'Complaints, closeout, and audit traceability.',
    sequence: 5,
  },
];

const STATES: WorkflowStateResult[] = [
  {
    stage_key: 'needs_collection',
    phase_key: 'app_planning',
    title: 'Needs Collection',
    description: 'Units submit their procurement needs for the fiscal year.',
    sequence: 1,
    is_terminal: false,
    requires_approval: false,
    requires_external_review: false,
    statute_reference: 'PPA 2007 s.18',
    assigned_roles: [],
    action_keys: ['needs.create', 'needs.submit'],
  },
  {
    stage_key: 'needs_analysis',
    phase_key: 'app_planning',
    title: 'Needs Analysis',
    description: 'Procurement consolidates and analyzes needs across all units.',
    sequence: 2,
    is_terminal: false,
    requires_approval: false,
    requires_external_review: false,
    statute_reference: 'PPA 2007 s.18',
    assigned_roles: ['comptroller_procurement'],
    action_keys: ['needs.analysis', 'needs.consolidate'],
  },
  {
    stage_key: 'needs_assessment',
    phase_key: 'app_planning',
    title: 'Needs Assessment',
    description: 'Head of Procurement endorses or rejects consolidated needs.',
    sequence: 3,
    is_terminal: false,
    requires_approval: true,
    requires_external_review: false,
    statute_reference: 'PPA 2007 s.18',
    assigned_roles: ['comptroller_procurement'],
    action_keys: ['needs.endorse', 'needs.return'],
  },
  {
    stage_key: 'budget_allocation_and_confirmation',
    phase_key: 'app_planning',
    title: 'Budget Allocation and Confirmation',
    description: 'Assign budget code and confirm funding readiness before committee review.',
    sequence: 4,
    is_terminal: false,
    requires_approval: true,
    requires_external_review: false,
    statute_reference: 'PPA 2007 s.16, s.18',
    assigned_roles: ['financial_unit_officer'],
    action_keys: ['budget.confirm'],
  },
  {
    stage_key: 'planning_committee_review',
    phase_key: 'app_planning',
    title: 'Planning Committee Review',
    description: 'Procurement Planning Committee reviews needs, aggregation, cost assumptions, and budget readiness.',
    sequence: 5,
    is_terminal: false,
    requires_approval: false,
    requires_external_review: false,
    statute_reference: 'PPA 2007 s.18(g), s.21',
    assigned_roles: [
      'comptroller_procurement',
      'procurement_secretary',
      'financial_unit_officer',
      'planning_statistics_officer',
    ],
    action_keys: ['app.review'],
  },
  {
    stage_key: 'app_approval',
    phase_key: 'app_planning',
    title: 'APP Approval',
    description: 'Accounting officer approves the annual procurement plan and releases it for execution.',
    sequence: 6,
    is_terminal: false,
    requires_approval: true,
    requires_external_review: false,
    statute_reference: 'PPA 2007 s.16(b)',
    assigned_roles: ['comptroller_procurement', 'accounting_officer'],
    action_keys: ['app.approve'],
  },
  {
    stage_key: 'procurement_initiation',
    phase_key: 'threshold_control',
    title: 'Procurement Initiation',
    description: 'Create a live procurement package from an approved APP line.',
    sequence: 10,
    is_terminal: false,
    requires_approval: false,
    requires_external_review: false,
    statute_reference: 'PPA 2007 s.16, s.19',
    assigned_roles: ['comptroller_procurement'],
    action_keys: ['procurement.initiate'],
  },
  {
    stage_key: 'threshold_resolution',
    phase_key: 'threshold_control',
    title: 'Threshold Resolution',
    description: 'Resolve the CGIS, Board, or BPP approval path for the procurement package.',
    sequence: 8,
    is_terminal: false,
    requires_approval: true,
    requires_external_review: false,
    statute_reference: 'PPA 2007 s.16, s.17',
    assigned_roles: ['comptroller_procurement'],
    action_keys: ['threshold.resolve'],
  },
  {
    stage_key: 'method_validation',
    phase_key: 'threshold_control',
    title: 'Method Validation',
    description: 'Validate open bidding by default and record any lawful exception.',
    sequence: 9,
    is_terminal: false,
    requires_approval: true,
    requires_external_review: false,
    statute_reference: 'PPA 2007 s.24-s.52',
    assigned_roles: ['comptroller_procurement', 'legal_reviewer'],
    action_keys: ['method.validate'],
  },
  {
    stage_key: 'solicitation',
    phase_key: 'procurement_execution',
    title: 'Advert / Invitation / EOI / RFP',
    description: 'Publish advert, invitation, EOI, or RFP in the lawful format.',
    sequence: 10,
    is_terminal: false,
    requires_approval: false,
    requires_external_review: false,
    statute_reference: 'PPA 2007 s.19, s.25, s.44-s.48',
    assigned_roles: ['comptroller_procurement'],
    action_keys: ['solicitation.publish'],
  },
  {
    stage_key: 'bid_opening',
    phase_key: 'procurement_execution',
    title: 'Bid Opening',
    description: 'Record public opening, attendance, and bid totals.',
    sequence: 11,
    is_terminal: false,
    requires_approval: false,
    requires_external_review: false,
    statute_reference: 'PPA 2007 s.30',
    assigned_roles: ['comptroller_procurement', 'evaluation_committee'],
    action_keys: ['bid_opening.record'],
  },
  {
    stage_key: 'evaluation',
    phase_key: 'procurement_execution',
    title: 'Evaluation',
    description: 'Evaluate only against the published criteria and issue recommendation.',
    sequence: 12,
    is_terminal: false,
    requires_approval: false,
    requires_external_review: false,
    statute_reference: 'PPA 2007 s.31-s.33, s.49-s.52',
    assigned_roles: ['technical_evaluator', 'financial_evaluator', 'evaluation_committee'],
    action_keys: ['evaluation.score', 'evaluation.report'],
  },
  {
    stage_key: 'tenders_board_review',
    phase_key: 'procurement_execution',
    title: 'Tenders Board Review',
    description: 'NIS Tenders Board review chaired by CGIS, with the board secretary maintaining the decision record.',
    sequence: 13,
    is_terminal: false,
    requires_approval: true,
    requires_external_review: false,
    statute_reference: 'PPA 2007 s.17, s.19, s.22',
    assigned_roles: ['tenders_board', 'tenders_board_secretary'],
    action_keys: ['approval.review', 'approval.decide'],
  },
  {
    stage_key: 'accounting_officer_review',
    phase_key: 'procurement_execution',
    title: 'CGIS Approval',
    description: 'CGIS exercises the direct low-value approval authority before award publication.',
    sequence: 14,
    is_terminal: false,
    requires_approval: true,
    requires_external_review: false,
    statute_reference: 'PPA 2007 s.16, s.20',
    assigned_roles: ['accounting_officer'],
    action_keys: ['accounting_officer.decide'],
  },
  {
    stage_key: 'bpp_no_objection',
    phase_key: 'procurement_execution',
    title: 'BPP No Objection',
    description: 'Submit and track the prior-review no-objection process when required.',
    sequence: 15,
    is_terminal: false,
    requires_approval: true,
    requires_external_review: false,
    statute_reference: 'PPA 2007 s.16, s.19',
    assigned_roles: ['bpp_liaison', 'bpp_reviewer'],
    action_keys: ['bpp.submit', 'bpp.review'],
  },
  {
    stage_key: 'award_and_publication',
    phase_key: 'post_award',
    title: 'Award and Publication',
    description: 'Notify outcome, debrief on request, and publish award.',
    sequence: 16,
    is_terminal: false,
    requires_approval: false,
    requires_external_review: false,
    statute_reference: 'PPA 2007 s.19, s.33',
    assigned_roles: ['comptroller_procurement'],
    action_keys: ['award.publish'],
  },
  {
    stage_key: 'contract_execution',
    phase_key: 'post_award',
    title: 'Contract Execution',
    description: 'Track contract signing, security, mobilisation, milestones, and variations.',
    sequence: 17,
    is_terminal: false,
    requires_approval: false,
    requires_external_review: false,
    statute_reference: 'PPA 2007 s.35-s.37',
    assigned_roles: ['contract_manager', 'comptroller_procurement'],
    action_keys: ['contract.manage'],
  },
  {
    stage_key: 'inspection_and_payment',
    phase_key: 'post_award',
    title: 'Inspection and Payment',
    description: 'Verify delivery, acceptance, and payment readiness.',
    sequence: 18,
    is_terminal: false,
    requires_approval: false,
    requires_external_review: false,
    statute_reference: 'PPA 2007 s.19, s.37',
    assigned_roles: ['inspection_officer', 'payment_officer'],
    action_keys: ['inspection.record', 'payment.track'],
  },
  {
    stage_key: 'closeout_and_audit',
    phase_key: 'review_and_oversight',
    title: 'Closeout and Audit',
    description: 'Close the procurement file and preserve the audit record.',
    sequence: 19,
    is_terminal: true,
    requires_approval: false,
    requires_external_review: false,
    statute_reference: 'PPA 2007 s.16, s.38',
    assigned_roles: ['audit_oversight', 'admin'],
    action_keys: ['closeout.archive'],
  },
  {
    stage_key: 'administrative_review',
    phase_key: 'review_and_oversight',
    title: 'Administrative Review',
    description: 'Handle bidder complaints and statutory review paths.',
    sequence: 20,
    is_terminal: false,
    requires_approval: false,
    requires_external_review: false,
    statute_reference: 'PPA 2007 s.54',
    assigned_roles: ['complaints_review_officer', 'accounting_officer', 'bpp_reviewer'],
    action_keys: ['complaint.review'],
  },
];

const TRANSITIONS: WorkflowTransitionResult[] = [
  { from_stage_key: 'needs_collection', to_stage_key: 'needs_analysis', condition: 'Needs submission period closes and procurement begins consolidation.' },
  { from_stage_key: 'needs_analysis', to_stage_key: 'needs_assessment', condition: 'Procurement has consolidated and analyzed needs across all units.' },
  { from_stage_key: 'needs_assessment', to_stage_key: 'budget_allocation_and_confirmation', condition: 'Head of Procurement endorses consolidated needs for budget integration.' },
  { from_stage_key: 'budget_allocation_and_confirmation', to_stage_key: 'planning_committee_review', condition: 'Budget allocation and confirmation completed for committee review.' },
  { from_stage_key: 'planning_committee_review', to_stage_key: 'app_approval', condition: 'Committee review complete and routed for APP approval.' },
  { from_stage_key: 'app_approval', to_stage_key: 'planning_committee_review', condition: 'APP approval returns the plan for committee rework.' },
  { from_stage_key: 'app_approval', to_stage_key: 'accounting_officer_review', condition: 'Comptroller Procurement forwards the committee-approved plan to CGIS for approval.' },
  { from_stage_key: 'accounting_officer_review', to_stage_key: 'procurement_initiation', condition: 'CGIS approves the plan and procurement may now be initiated.' },
  { from_stage_key: 'procurement_initiation', to_stage_key: 'threshold_resolution', condition: 'Live procurement request has been created.' },
  { from_stage_key: 'threshold_resolution', to_stage_key: 'method_validation', condition: 'Threshold route and approval path have been resolved.' },
  { from_stage_key: 'method_validation', to_stage_key: 'solicitation', condition: 'Method is lawful and approved.' },
  { from_stage_key: 'solicitation', to_stage_key: 'bid_opening', condition: 'Submission period closes.' },
  { from_stage_key: 'bid_opening', to_stage_key: 'evaluation', condition: 'Opening record is complete.' },
  { from_stage_key: 'evaluation', to_stage_key: 'accounting_officer_review', condition: 'CGIS direct approval applies within low-value threshold.' },
  { from_stage_key: 'evaluation', to_stage_key: 'tenders_board_review', condition: 'Board review applies within board or BPP threshold.' },
  { from_stage_key: 'tenders_board_review', to_stage_key: 'award_and_publication', condition: 'Board approval is final within threshold.' },
  { from_stage_key: 'tenders_board_review', to_stage_key: 'bpp_no_objection', condition: 'BPP prior review applies after board endorsement.' },
  { from_stage_key: 'accounting_officer_review', to_stage_key: 'award_and_publication', condition: 'CGIS direct approval is complete.' },
  { from_stage_key: 'bpp_no_objection', to_stage_key: 'award_and_publication', condition: 'No-objection is issued.' },
  { from_stage_key: 'award_and_publication', to_stage_key: 'contract_execution', condition: 'Contract has been signed.' },
  { from_stage_key: 'contract_execution', to_stage_key: 'inspection_and_payment', condition: 'Milestone or delivery is ready for inspection.' },
  { from_stage_key: 'inspection_and_payment', to_stage_key: 'closeout_and_audit', condition: 'Final acceptance and payment are complete.' },
  { from_stage_key: 'solicitation', to_stage_key: 'administrative_review', condition: 'A complaint has been filed.' },
  { from_stage_key: 'evaluation', to_stage_key: 'administrative_review', condition: 'A complaint has been filed.' },
  { from_stage_key: 'award_and_publication', to_stage_key: 'administrative_review', condition: 'A complaint has been filed.' },
];

const ROLE_TASKS: WorkflowRoleTaskResult[] = [
  { role_key: 'financial_unit_officer', role_label: 'Budget Officer', stage_key: 'budget_allocation_and_confirmation', task_description: 'Allocate budget code and confirm funds for the request.', completion_summary: 'Budget allocation and confirmation are recorded.' },
  { role_key: 'comptroller_procurement', role_label: 'Comptroller Procurement (Chair)', stage_key: 'planning_committee_review', task_description: 'Chair the Procurement Planning Committee and validate the consolidated needs package.', completion_summary: 'Committee review is complete under the accounting officer.' },
  { role_key: 'procurement_secretary', role_label: 'Procurement Secretary', stage_key: 'planning_committee_review', task_description: 'Record committee deliberations and maintain the planning committee trail.', completion_summary: 'Committee proceedings are properly recorded.' },
  { role_key: 'financial_unit_officer', role_label: 'Financial Unit Officer', stage_key: 'planning_committee_review', task_description: 'Review funding alignment and confirm budget integrity within the committee.', completion_summary: 'Funding position is confirmed for committee review.' },
  { role_key: 'planning_statistics_officer', role_label: 'Planning, Research and Statistics', stage_key: 'planning_committee_review', task_description: 'Validate aggregation, sequencing, and annual planning assumptions.', completion_summary: 'Planning package is coherent.' },
  { role_key: 'comptroller_procurement', role_label: 'Comptroller Procurement', stage_key: 'app_approval', task_description: 'Approve the annual procurement plan as accounting officer and release it for execution.', completion_summary: 'APP is approved for execution per PPA s.16(b).' },
  { role_key: 'accounting_officer', role_label: 'CGIS', stage_key: 'app_approval', task_description: 'Provide Comptroller General of Immigration Service concurrence before the APP is released for execution.', completion_summary: 'APP approval includes CGIS control.' },
  { role_key: 'comptroller_procurement', role_label: 'Comptroller Procurement', stage_key: 'procurement_initiation', task_description: 'Open a procurement package from an approved APP line as head of the procurement unit.', completion_summary: 'Execution stays tied to APP control.' },
  { role_key: 'comptroller_procurement', role_label: 'Comptroller Procurement', stage_key: 'threshold_resolution', task_description: 'Resolve whether the case falls to CGIS, the NIS Tenders Board, or BPP prior review as head of the procurement unit.', completion_summary: 'Approval path and external review trigger are explicit.' },
  { role_key: 'comptroller_procurement', role_label: 'Comptroller Procurement', stage_key: 'method_validation', task_description: 'Approve the validated procurement method and authorize movement to solicitation.', completion_summary: 'Method validation is accepted and the tender can proceed to publication.' },
  { role_key: 'legal_reviewer', role_label: 'Legal Reviewer', stage_key: 'method_validation', task_description: 'Validate lawful procurement method and exceptions.', completion_summary: 'Method choice is compliant.' },
  { role_key: 'comptroller_procurement', role_label: 'Comptroller Procurement', stage_key: 'solicitation', task_description: 'Publish advert, invitation, EOI, or RFP using the required route.', completion_summary: 'Competition is opened lawfully through the approved publication route.' },
  { role_key: 'technical_evaluator', role_label: 'Technical Evaluator', stage_key: 'evaluation', task_description: 'Perform technical scoring.', completion_summary: 'Technical responsiveness is assessed.' },
  { role_key: 'financial_evaluator', role_label: 'Financial Evaluator', stage_key: 'evaluation', task_description: 'Perform arithmetic and financial review.', completion_summary: 'Commercial comparison is accurate.' },
  { role_key: 'evaluation_committee', role_label: 'Evaluation Committee', stage_key: 'evaluation', task_description: 'Issue consolidated recommendation.', completion_summary: 'Approval pack is ready.' },
  { role_key: 'tenders_board_secretary', role_label: 'Tenders Board Secretary', stage_key: 'tenders_board_review', task_description: 'Prepare board papers and record the decision log for the NIS Tenders Board chaired by CGIS.', completion_summary: 'Board traceability is complete.' },
  { role_key: 'tenders_board', role_label: 'NIS Tenders Board', stage_key: 'tenders_board_review', task_description: 'Approve, reject, or endorse recommendation for BPP prior review under the chairmanship of CGIS.', completion_summary: 'Board decision is recorded with governance rationale.' },
  { role_key: 'accounting_officer', role_label: 'CGIS', stage_key: 'accounting_officer_review', task_description: 'Exercise direct low-value approval authority.', completion_summary: 'CGIS decision is recorded before award publication.' },
  { role_key: 'bpp_liaison', role_label: 'BPP Liaison', stage_key: 'bpp_no_objection', task_description: 'Submit prior-review pack to BPP.', completion_summary: 'Regulatory submission is complete.' },
  { role_key: 'bpp_reviewer', role_label: 'BPP Reviewer', stage_key: 'bpp_no_objection', task_description: 'Record BPP outcome and queries.', completion_summary: 'No-objection status is traceable.' },
  { role_key: 'comptroller_procurement', role_label: 'Comptroller Procurement', stage_key: 'award_and_publication', task_description: 'Issue award notice and publication.', completion_summary: 'Award is legally communicated.' },
  { role_key: 'contract_manager', role_label: 'Contract Manager', stage_key: 'contract_execution', task_description: 'Track performance security, milestones, and variations.', completion_summary: 'Contract is controlled post-award.' },
  { role_key: 'inspection_officer', role_label: 'Inspection Officer', stage_key: 'inspection_and_payment', task_description: 'Record inspection and acceptance.', completion_summary: 'Payment readiness is evidence-backed.' },
  { role_key: 'payment_officer', role_label: 'Payment Officer', stage_key: 'inspection_and_payment', task_description: 'Track payment path after acceptance.', completion_summary: 'Disbursement stays controlled.' },
  { role_key: 'audit_oversight', role_label: 'Audit and Oversight', stage_key: 'closeout_and_audit', task_description: 'Review closeout pack and audit trail.', completion_summary: 'File is ready for oversight.' },
  { role_key: 'complaints_review_officer', role_label: 'Administrative Review Officer', stage_key: 'administrative_review', task_description: 'Manage complaint workflow under Section 54.', completion_summary: 'Complaint path is traceable and timely.' },
];

const DATABASE_TABLES: string[] = [
  'procurement_workflow.procurement_plans',
  'procurement_workflow.procurement_plan_items',
  'procurement_workflow.approval_thresholds',
  'identity.organizational_positions',
  'procurement_workflow.governance_bodies',
  'procurement_workflow.governance_body_memberships',
  'procurement_workflow.tenders',
  'procurement_workflow.bid_opening_sessions',
  'procurement_workflow.evaluation_reports',
  'procurement_workflow.bpp_no_objections',
  'procurement_workflow.contract_awards',
  'procurement_workflow.contracts',
  'procurement_workflow.inspections',
  'procurement_workflow.budget_commitments',
  'procurement_workflow.workflow_stage_catalog',
  'procurement_workflow.workflow_stage_transitions',
  'procurement_workflow.workflow_role_tasks',
];

export const PHASES_CATALOG = PHASES;
export const STATES_CATALOG = STATES;
export const TRANSITIONS_CATALOG = TRANSITIONS;
export const ROLE_TASKS_CATALOG = ROLE_TASKS;
export const DATABASE_TABLES_CATALOG = DATABASE_TABLES;

export function getPhases(): readonly WorkflowPhaseResult[] {
  return PHASES;
}

export function getStates(): readonly WorkflowStateResult[] {
  return STATES;
}

export function getTransitions(): readonly WorkflowTransitionResult[] {
  return TRANSITIONS;
}

export function getRoleTasks(): readonly WorkflowRoleTaskResult[] {
  return ROLE_TASKS;
}

export function getFallbackThresholds(): WorkflowThresholdBandResult[] {
  return [
    {
      procurement_type: 'Goods/Works/Services',
      min_amount: 0,
      max_amount: 50_000_000,
      approval_route: 'CGIS Direct Approval',
      approval_authority_code: 'CGIS_DIRECT_APPROVAL',
      approval_authority_label: 'CGIS Direct Approval',
      requires_cgis_approval: true,
      requires_board: false,
      requires_bpp: false,
      governance_body_id: null,
      governance_body_name: null,
      notes: 'Fallback band when live threshold records are unavailable.',
    },
    {
      procurement_type: 'Goods/Works/Services',
      min_amount: 50_000_000,
      max_amount: 100_000_000,
      approval_route: 'NIS Tenders Board Review',
      approval_authority_code: 'NIS_TENDERS_BOARD',
      approval_authority_label: 'NIS Tenders Board (Chair: CGIS)',
      requires_cgis_approval: false,
      requires_board: true,
      requires_bpp: false,
      governance_body_id: null,
      governance_body_name: 'NIS Tenders Board',
      notes: 'Board route applies within entity authority under the chairmanship of CGIS.',
    },
    {
      procurement_type: 'Goods/Works/Services',
      min_amount: 100_000_000,
      max_amount: null,
      approval_route: 'NIS Tenders Board + BPP No Objection',
      approval_authority_code: 'BPP_PRIOR_REVIEW',
      approval_authority_label: 'NIS Tenders Board + BPP No Objection',
      requires_cgis_approval: false,
      requires_board: true,
      requires_bpp: true,
      governance_body_id: null,
      governance_body_name: 'NIS Tenders Board',
      notes: 'BPP prior review applies after NIS Tenders Board endorsement chaired by CGIS.',
    },
  ];
}

export function build(
  currentRole: string | null | undefined,
  thresholds: WorkflowThresholdBandResult[],
  thresholdSource: string,
): WorkflowBlueprintResult {
  return {
    title: 'PPA 2007 Procurement Workflow Blueprint',
    description: 'Unified APP, threshold, procurement execution, and review flow for the internal portal.',
    threshold_source: thresholdSource,
    current_role: currentRole ?? null,
    database_tables: DATABASE_TABLES,
    phases: PHASES,
    states: STATES,
    transitions: TRANSITIONS,
    role_tasks: ROLE_TASKS,
    thresholds,
  };
}
